export const HIGHLIGHT_LAYER = 'HIGHLIGHT_LAYER'
export const SELECT_ARTBOARD = 'SELECT_ARTBOARD'
export const SELECT_LAYER = 'SELECT_LAYER'
export const TOGGLE_ARTBOARD_ITEM = 'TOGGLE_ARTBOARD_ITEM'
